### ISSUE TITLE
Problems when interface is disabled (rfkill)

### ISSUE THREAD

**Issue by The-Compiler** [joukewitteveen/netctl#148] opened 2017-03-01 16:08 UTC
When I try to start a profile on a interface which is disabled via a hardware switch, I get:

```
Mar 01 16:51:38 hooch sudo[11387]:  florian : TTY=unknown ; PWD=/home/florian ; USER=root ; COMMAND=/usr/bin/netctl start sis
Mar 01 16:51:38 hooch sudo[11387]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 01 16:51:38 hooch systemd[1]: Starting Networking for netctl profile sis...
Mar 01 16:51:38 hooch network[11392]: Starting network profile 'sis'...
Mar 01 16:51:38 hooch wpa_actiond[542]: Terminating wpa_actiond session for interface 'wlan'
Mar 01 16:51:43 hooch network[11392]: Failed to bring the network up for profile 'sis'
Mar 01 16:51:43 hooch systemd[1]: netctl@sis.service: Main process exited, code=exited, status=1/FAILURE
Mar 01 16:51:44 hooch systemd[1]: Failed to start Networking for netctl profile sis.
```

so far, so good (though a better error message would be nice). When I then enable it and try again, the interface is already up:

```
Mar 01 16:52:08 hooch sudo[11883]:  florian : TTY=unknown ; PWD=/home/florian ; USER=root ; COMMAND=/usr/bin/netctl start sis
Mar 01 16:52:08 hooch sudo[11883]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 01 16:52:08 hooch systemd[1]: Starting Networking for netctl profile sis...
Mar 01 16:52:08 hooch network[11888]: Starting network profile 'sis'...
Mar 01 16:52:08 hooch network[11888]: The interface of network profile 'sis' is already up
Mar 01 16:52:08 hooch systemd[1]: netctl@sis.service: Main process exited, code=exited, status=1/FAILURE
Mar 01 16:52:08 hooch systemd[1]: Failed to start Networking for netctl profile sis.
```

When I bring it down manually and then try again, it fails because the wpa config file still exists:

```
Mar 01 16:52:22 hooch sudo[12001]:  florian : TTY=unknown ; PWD=/home/florian ; USER=root ; COMMAND=/usr/bin/netctl start sis
Mar 01 16:52:22 hooch sudo[12001]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 01 16:52:22 hooch systemd[1]: Starting Networking for netctl profile sis...
Mar 01 16:52:22 hooch network[12006]: Starting network profile 'sis'...
Mar 01 16:52:22 hooch network[12006]: Could not create a wpa config file for interface 'wlan'
Mar 01 16:52:22 hooch network[12006]: Failed to bring the network up for profile 'sis'
Mar 01 16:52:22 hooch systemd[1]: netctl@sis.service: Main process exited, code=exited, status=1/FAILURE
Mar 01 16:52:22 hooch systemd[1]: Failed to start Networking for netctl profile sis.
```

After removing that manually (`rm /run/network/wpa_supplicant_wlan.conf`) it finally works.

I'm not sure what the actual issues are here - some thoughts of what'd help:

- Better error message when bringing the interface up failed (like the output of bringing it up)
- Clean up properly (remove the config file) when connecting failed
- Ignoring an interface already being up?
- Always removing an existing config file before creating a new one?

**Comment by joukewitteveen** [comment] 2017-03-01 16:17
It could be that we don't clean up in some situation where we fail. That should then be fixed. We will not ignore any errors or remove existing files: unclean environments are fatal to netctl. That is by design.

I noted a mention of wpa_actiond in one of your logs. Could it be that you have netctl-auto and some other netctl service both enabled?

**Comment by The-Compiler** [comment] 2017-03-01 16:37
I do indeed have `netctl-auto` enabled - here I wondered why it didn't work, and then started it by hand.

**Comment by joukewitteveen** [comment] 2017-03-01 16:44
You need to be more precise in what is causing this unexpected behavior. I see the following in your logs:
```
Mar 01 16:51:38 hooch wpa_actiond[542]: Terminating wpa_actiond session for interface 'wlan'
```
which is emitted by `netctl-auto`, and
```
Mar 01 16:51:44 hooch systemd[1]: Failed to start Networking for netctl profile sis.
```
which is caused by a failing `netctl@sis.service`.
It should be no surprise that the two interfere when they target the same interface.

**Comment by joukewitteveen** [comment] 2017-03-03 18:31
While I still don't know how to replicate your issue, I have sent [a patch](https://lists.archlinux.org/pipermail/arch-projects/2017-March/004484.html) to the arch-projects mailinglist that requires the interface to be down when starting `netctl-auto` and brings the interface back down when `netctl-auto` fails to start up properly.

**Comment by The-Compiler** [comment] 2017-03-06 07:29
I can still (mostly) reproduce this with netctl-auto disabled.

With WiFi disabled via the hardware button, connecting fails (which is expected). When enabling it again and trying to connect again, `/run/network/wpa_supplicant_wlan.conf` still exists and thus connecting still fails.

**Comment by joukewitteveen** [comment] 2017-03-06 09:22
Ah, I traced your bug and indeed, the generated configuration file could be left behind. I will improve the cleanup in the next version, which will be released soon.

Please, in the future improve your bug reports by adding a step-by-step description of _exactly_ how to reproduce the issue you are seeing, together with as much relevant debugging output you can gather.

**Comment by joukewitteveen** [comment] 2017-03-14 17:17
8ccfe9713b7a92102f5d8aa9c5351f008f658dcd

**Closed by joukewitteveen** 2017-03-14 17:17 UTC
